# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
