# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/akonadi-mime': '@same'
    'frameworks/kmime': '@latest-kf6'
    'pim/pimcommon': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 enable-lsan: True
